@host=http://localhost:8080/profiles
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTY4NjQ4Nzk4NDM0MiwidXNlcm5hbWUiOiJMeWRpYSIsImlhdCI6MTY4NjUzMjc5OCwiZXhwIjoxNjg2NTM2Mzk4fQ.4gtlHc1m8OtJlnY5io_KG_oat6m7R6wqCFIEUIXAswo

GET {{host}} HTTP/1.1

### 用户登录
POST {{host}}/login HTTP/1.1
Content-Type: application/json


{
    "username": "Lydia",
    "password": "123456"
}


### 用户注册
POST {{host}}/register HTTP/1.1
Content-Type: application/json

{
    "username": "Mimi",
    "password": "123456"
}

###删除用户
DELETE {{host}}/users/1686533054805 HTTP/1.1
Authorization: Bearer {{token}}

### 获取用户列表
GET {{host}}/users/1686487640238 HTTP/1.1
Authorization: Bearer {{token}}

### 更新用户信息
PATCH {{host}}/users/1686488009205 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "username": "Jennifer",
    "nickname": "珍妮弗er",
    "email": "jennifer@qq.com",
    "intro": "大家好，我是珍妮弗！"
}









### 添加message留言
POST {{host}}/message/1686487984342 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nickname": "Lydia",
    "content": "我是Lydia，这是我的第二条留言！"
}


### 删除message留言
DELETE  {{host}}/message/1686533250418 HTTP/1.1
Authorization: Bearer {{token}}


### 更新message留言
PATCH {{host}}/message/1685931462838 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "我第四次修改了留言"
}

### 查找message留言
GET {{host}}/message/1686487984342?query=w&page=1 HTTP/1.1
Authorization: Bearer {{token}}